title: Sound Mac Guy
description: >
  I used to be a sound engineer. Now I manage Apple stuff.
baseurl: ""
url: ""
github_username: neilmartin83
slack_username: neilmartin83
theme: minima
plugins:
  - jekyll-feed
  - jekyll-paginate
paginate: 10
paginate_path: "/page/:num"
